### ISSUE TITLE
Line endings in `nom`

### ISSUE THREAD

**Issue by jschpp** [icub3d/the-wall-puzzle#1]
I was just watching your yt video on this puzzle here.

And while you were explaing your `nom` parser I stumbled about your line separating.
https://github.com/icub3d/the-wall-puzzle/blob/aa5a892da345e38eb575815e1547fdd70a158727/src/main.rs#L79

This will break on `\r\n` formatted files. That should not be a problem per se but I wanted to point you to [`nom::character::complete::line_ending`](https://docs.rs/nom/latest/nom/character/complete/fn.line_ending.html) as the alternative to handle those specific endings a smidgen more robust.

Thank you for your excellent content 😄

**Comment by icub3d** [comment]
:heart: Thanks! I've fixed it. :heart:
